protected/models/Event.php
<?php

/**
 * This is the model class for table "tbl_event".
 *
 * The followings are the available columns in table 'tbl_event':
 * @property integer $id
 * @property string $name
 * @property string $schedule
 * @property string $place
 * @property string $remark
 * @property integer $create_by
 * @property string $create_at
 * @property integer $updated_by
 * @property string $updated_at
 */
class Event extends CActiveRecord
{
	public $date_schedule;
	public $time_schedule;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_event';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('name, schedule, place', 'required'),
			array('name, remark', 'length', 'max'=>250),
			array('surat', 'length', 'max'=>128),
			array('place', 'length', 'max'=>150),
			array('schedule, disposisi_nama, disposisi_jabatan, tgl_surat', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, schedule, place, remark, surat, disposisi_nama, disposisi_jabatan, tgl_surat, is_active', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Acara',
			'schedule' => 'Tanggal',
			'date_schedule' => 'Tanggal Acara',
			'time_schedule' => 'Jam Acara',
			'place' => 'Tempat',
			'surat' => 'No. Surat',
			'tgl_surat' => 'Tgl. Surat',
			'disposisi_nama' => 'Disposisi Nama',
			'disposisi_jabatan' => 'Disposisi Jabatan',
			'remark' => 'Keterangan',
			'create_by' => 'Dibuat oleh',
			'create_at' => 'Dibuat pada',
			'updated_by' => 'Diubah oleh',
			'updated_at' => 'Diubah pada',
			'is_active' => 'Aktif'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('name',$this->name,true);
		$criteria->compare('schedule',$this->schedule,true);
		$criteria->compare('surat',$this->surat,true);
		$criteria->compare('place',$this->place,true);
		$criteria->compare('disposisi_nama',$this->disposisi_nama,true);
		$criteria->compare('disposisi_jabatan',$this->disposisi_jabatan,true);
		$criteria->compare('is_active',$this->is_active,true);

		$criteria->order = 'schedule DESC';

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Event the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function beforeSave()
	{
		$this->updated_by = Yii::app()->user->id;
		$this->updated_at = new CDbExpression('NOW()');

		if ($this->isNewRecord) {
			$this->create_by = $this->updated_by;
			$this->create_at = $this->updated_at;
		}
		return parent::beforeSave();
	}
	public function afterFind()
	{
		$dtools = new CDateFormatter('id_ID');
		$this->date_schedule = $dtools->format('eeee / d MMM yyyy', $this->schedule);
		$this->time_schedule =  date('H:i', strtotime($this->schedule));

		return parent::afterFind();
	}
	public function getByPage($pageNumber, $limitRow, $startInterval, $endInterval)
	{
		$offset = ($pageNumber - 1) * $limitRow;

		$criteria = new CDbCriteria();

		if (! is_null($startInterval) && ! is_null($endInterval)) {
			$criteria->addCondition('schedule >= DATE_ADD(CURDATE(), INTERVAL :date_from DAY) and schedule <= DATE_ADD(CURDATE(), INTERVAL :date_to DAY)');
			$criteria->params[':date_from'] = $startInterval;
			$criteria->params[':date_to']   = $endInterval+1;
		}
		$criteria->limit = $limitRow;
		$criteria->offset = $offset;
		$criteria->order = 'schedule ASC';

		return $this->findAll($criteria);
	}
	public function todayText() 
	{
		return date('d-m-Y', strtotime($this->schedule)) == date('d-m-Y') ? 'today' : null;
	}
}

protected/controllers/EventController.php
<?php

class EventController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	// public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions'=>array('list'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index', 'create','update', 'delete', 'fetchPlace','export', 'toggle'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Event;

		if(isset($_POST['Event']))
		{
			$model->attributes=$_POST['Event'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(isset($_POST['Event']))
		{
			$model->attributes=$_POST['Event'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via index grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Event('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Event']))
			$model->attributes=$_GET['Event'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Event the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Event::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Event $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='event-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionFetchPlace($term)
	{				
		$criteria = new CDbCriteria();
		$criteria->select = 'DISTINCT place AS place';
		$criteria->addCondition("place LIKE '%".$term."%'");
		$list = Event::model()->findAll($criteria);
		$result = array();
		if (! empty($list)) {
			foreach ($list as $row) {
				array_push($result, $row->place);
			}
		} 
		echo CJSON::encode($result);
	}
	public function actionList()
	{
		/*
		{
		    "header": ["No Surat", "Acara", "Hari/Tanggal", "Tempat", "Waktu", "Disposisi"],
		    "datum": [{
		        "data": ["No1.00200e", "Seminar Kebersihan", "Senin / 22-01-2016", "Alun-Alun", "19:00", "Mochamad Karsa"],
		        "event": ""
		    }, {
		        "data": ["No1.00200e", "Seminar Kesehatan", "Selasa / 25-01-2016", "Balai Kota", "09:00", "Andre"],
		        "event": "today"
		    }, {
		        "data": ["No1.00200e", "Makan - makan", "Selasa / 25-01-2016", "Hotal Ibis", "18:00", "Andre"],
		        "event": "today"
		    }, {
		        "data": ["No1.00200e", "Seminar Keagamaan", "Rabu / 23-01-2016", "Masjid Jamek Malang", "18:00", "Kiko Insa"],
		        "event": ""
		    }, {
		        "data": ["No1.00200e", "Apel", "23-01-2016", "Kamis / Balai Kota", "18:00", "Kiko Insa"],
		        "event": ""
		    }, {
		        "data": ["No1.00200e", "Seminar Keagamaan", "Jumat / 23-01-2016", "Masjid Jamek Malang", "18:00", "Kiko Insa"],
		        "event": ""
		    }],
		    "page_now": 1
		}
		*/
		/*
		{
		    "column": ["surat" => "No Surat", "name" => "Acara", "schedule", "place", "time", "disposisi_jabatan"]
		}
		*/

		/********
		 * Keterangan :
		 * untuk date_to
		 * 0 = Hari ini
		 * 1 = Besok
		 * 2 = Lusa
		 * 7 = Minggu depan
		 * 30 = Bulan Depan
		 * untuk date_from
		 * 0 = Hari ini
		 * -1 = Kemarin
		 * -2 = Kemarin lusa
		 * -7 = Minggu kemarin
		 * -30 = Bulan kemarin
		 *******/


		$modelSetting = Setting::getDefault();

		$criteria = new CDbCriteria();
		if (! is_null($modelSetting->date_from) && ! is_null($modelSetting->date_to)) {
			$criteria->addCondition('schedule >= DATE_ADD(CURDATE(), INTERVAL :date_from DAY) and schedule <= DATE_ADD(CURDATE(), INTERVAL :date_to DAY)');
			$criteria->params[':date_from'] = $modelSetting->date_from;
			$criteria->params[':date_to']   = $modelSetting->date_to + 1;
		}
		$dataCount = Event::model()->count($criteria);
		/****
		 * Paging
		 ******/
		$halaman=ceil($dataCount / $modelSetting->limit_row);
		$page = (isset($_GET['page'])) ? (int)$_GET['page'] : 1;
		if($page >= $halaman){
			$page = 1;
		}

		$list = Event::model()->getByPage(
			$page
			, $modelSetting->limit_row
			, $modelSetting->date_from
			, $modelSetting->date_to
		);
		$dataList = array();
		$columnHeader = CJSON::decode($modelSetting->limit_column);
		if (! empty($list)) {
			foreach ($list as $event) {
				$arrayValues = array();
				foreach ($columnHeader as $field => $alias) {
					array_push($arrayValues, $event->{$field});
				}
				array_push($dataList, array(
					'data'=>$arrayValues,
					'event'=>$event->todayText(),
				));
			}
		}

		header('Content-type: application/json');

    	$response = array(
    		'header'  =>array_values($columnHeader),
    		'datum'   =>$dataList,
    		'page_now'=>$page,
    	);
    	echo CJSON::encode($response);
		Yii::app()->end();
	}
	public function actionExport($surat=null,$name=null,$schedule=null,$place=null,$disposisi_nama=null,$disposisi_jabatan=null)
	{
	    $model = new Event();
	    $dataProvider = $model->search();
	    if (!empty($surat)) {
	    	$dataProvider->criteria->addCondition("surat LIKE '%".$surat."%'");
		}
		if (!empty($name)) {
			echo $name;
			$dataProvider->criteria->addCondition("name LIKE '%".$name."%'");			
		}
		if (!empty($schedule)) {
			$dataProvider->criteria->addCondition("schedule = '".$schedule."'");			
		}
		if (!empty($place)) {
			$dataProvider->criteria->addCondition("place LIKE '%".$place."%'");			
		}
		if (!empty($disposisi_nama)) {
			$dataProvider->criteria->addCondition("disposisi_nama LIKE '%".$disposisi_nama."%'");			
		}
		if (!empty($disposisi_jabatan)) {
			$dataProvider->criteria->addCondition("disposisi_jabatan LIKE '%".$disposisi_jabatan."%'");			
		}
		$this->widget('ext.eexcelview.EExcelView', 
	    	array(
	        	'grid_mode'=>'export',
	        	'title' => 'Daftar Acara',
				'dataProvider' => $dataProvider,
				'filter' => $model,
				'columns' => 
					array(
						'surat',
						'tgl_surat',
						'name',
						'schedule',
						'place',
						'disposisi_nama',
						'disposisi_jabatan',
					),
			)
		);
		
	}

	public function actionToggle($id)
	{  	
		$model = Event::model()->findByPk($id);
		$aktif = $model->is_active;
		
		if($aktif==1) {
			$model->is_active = 0;
			$model->save();
		} else {
			$model->is_active = 1;
			$model->save();
		}
		$this->redirect(array('index'));
	}
}

protected/views/event/_form.php
<?php
/* @var $this EventController */
/* @var $model Event */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'event-form',
	'enableAjaxValidation'=>false,
		'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
        'class'=>"form-horizontal"
    ),
)); ?>

	<p class="alert alert-block alert-success">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php $errornya= $form->errorSummary($model); 
	if (strlen($errornya)>1) { ?>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">
				<i class="ace-icon fa fa-times"></i>
			</button>
			<strong>
				<i class="ace-icon fa fa-times"></i>
				Awas!
			</strong>
			<?php echo $form->errorSummary($model); ?>
			<br />
		</div>	
	<?php	} ?>
	
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'surat'); ?> </label>
		<div class="col-sm-9">
			<?php echo $form->textField($model,'surat',array('size'=>60,'maxlength'=>128,  'id'=>"surat", 'placeholder'=>"Nomor Surat", 'class'=>"col-xs-12")); ?>
			<?php echo $form->error($model,'surat'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'tgl_surat'); ?> </label>
		<div class="col-sm-3">
			<div class="input-group">
				<?php echo $form->textField($model,'tgl_surat', array('id' => 'id-date-picker-1', 'class' => 'form-control date-picker',  'data-date-format'=>"yyyy-mm-dd" )); ?>
				<span class="input-group-addon">
					<i class="fa fa-calendar-o bigger-110"></i>
				</span>
			</div>
			<?php echo $form->error($model,'tgl_surat'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'schedule'); ?> </label>
		<div class="col-sm-3">
			<div class="input-group">
				<?php echo $form->textField($model,'schedule', array('id' => 'date-timepicker1', 'class' => 'form-control')); ?>
				<span class="input-group-addon">
					<i class="fa fa-clock-o bigger-110"></i>
				</span>
			</div>
			<?php echo $form->error($model,'schedule'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'name'); ?> </label>
		<div class="col-sm-9">
			<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>250,  'id'=>"form-field-1", 'placeholder'=>"Acara", 'class'=>"col-xs-12")); ?>
			<?php echo $form->error($model,'name'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'place'); ?> </label>
		<div class="col-xs-12 col-sm-9">
			<?php $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
			    'model'=>$model,
			    'attribute'=>'place',
			    'sourceUrl'=>Yii::app()->createUrl('event/fetchPlace'),
				    'options'=>array(
				        'minLength'=>'2',
				    ),
				    'htmlOptions'=>array('size'=>40),
	    		)); 
	    	?>
			<?php echo $form->error($model,'place'); ?>
		</div>
	</div> 

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'disposisi_nama'); ?> </label>
		<div class="col-sm-9">		
			<?php echo $form->textArea($model,'disposisi_nama',array('size'=>60,'maxlength'=>250,  'id'=>"form-field-11", 'placeholder'=>"Disposisi Nama", 'class'=>"col-xs-12")); ?>
			<?php echo $form->error($model,'disposisi_nama'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'disposisi_jabatan'); ?> </label>
		<div class="col-sm-9">		
			<?php echo $form->textArea($model,'disposisi_jabatan',array('size'=>60,'maxlength'=>250,  'id'=>"form-field-11", 'placeholder'=>"Disposisi Nama", 'class'=>"col-xs-12")); ?>
			<?php echo $form->error($model,'disposisi_jabatan'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'remark'); ?> </label>
		<div class="col-sm-9">
			<?php echo $form->textArea($model,'remark',array('class'=> 'form-control', 'rows'=>'6','maxlength'=>250 )); ?>
		</div>
	</div>

	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<?php echo CHtml::submitButton($model->isNewRecord ? ' Tambahkan' : '  Simpan', 
			array('class' => 'btn btn-primary', 'type' => 'submit')); ?>
			
			
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php
$scripts=<<<EOL
				$('.date-picker').datepicker({
					autoclose: true,
					todayHighlight: true,
					dateFormat: 'yy-mm-dd' 
				})
				//show datepicker when clicking on the icon
				.next().on(ace.click_event, function(){
					$(this).prev().focus();
				});
					
				//Android's default browser somehow is confused when tapping on label which will lead to dragging the task
				//so disable dragging when clicking on label
				var agent = navigator.userAgent.toLowerCase();
				if("ontouchstart" in document && /applewebkit/.test(agent) && /android/.test(agent))
				  $('#tasks').on('touchstart', function(e){
					var li = $(e.target).closest('#tasks li');
					if(li.length == 0)return;
					var label = li.find('label.inline').get(0);
					if(label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation() ;
				});
$('#date-timepicker1').datetimepicker({
	format: 'YYYY-MM-DD HH:mm',
	sideBySide: true,
	pickerPosition: "bottom-left"
}).next().on(ace.click_event, function(){
	$(this).prev().focus();
});
$('.chosen-select').chosen({allow_single_deselect:true});
EOL;

/*******
 * JavaScript
 *******/
Yii::app()->clientScript->registerScript('create-event', $scripts, CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl ."/backend/js/bootstrap-datetimepicker.min.js", CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl ."/backend/js/bootstrap-datepicker.min.js", CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl ."/backend/js/chosen.jquery.min.js", CClientScript::POS_END);

/*******
 * Css
 *******/
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl ."/backend/css/datepicker.min.css");
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl ."/backend/css/bootstrap-datetimepicker.min.css");
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl ."/backend/css/chosen.min.css");

protected/views/event/admin.php
<?php
/* @var $this EventController */
/* @var $model Event */

$this->breadcrumbs=array(
	'Kegiatan'=>array('index'),
	'Jadwal',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$('#event-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
$title = "Daftar Kegiatan";
?>

<h1><?php echo $title;?></h1>
<div class="clearfix">
	<div class="pull-right tableTools-container">
		<div class="btn-group btn-overlap">
		<?php 
			if(array_key_exists('Event', $_GET)) { 
				$saring='?r=event/export';
				foreach ($_GET['Event'] as $key =>$value) {
					$saring=$saring.'&'.$key.'='.$value;
				} ?>
				<a href="../index.php<?php echo $saring; ?>"  class="DTTT_button btn btn-white btn-primary  btn-bold" id="ToolTables_dynamic-table_1" tabindex="0" aria-controls="dynamic-table" > Excel</a>
			<?php 
			} else { 
				?>
				<a onclick="export_function();" class="btn btn-app btn-grey btn-xs radius-4" id="ToolTables_dynamic-table_1" tabindex="0" aria-controls="dynamic-table"> 
					<span><i class="ace-icon fa fa-file-excel-o bigger-160"></i></span>
					<div style="position: absolute; left: 0px; top: 0px; width: 39px; height: 35px; z-index: 99;" title="" data-original-title="Export to CSV">
					</div>
				</a> <?php
		} ?>
		</div>
	</div>
</div>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'event-grid',
	'dataProvider'=>$model->search(),
	'itemsCssClass'=>'table table-striped table-bordered table-hover',
	'enableSorting'=>true,
	'filter'=>$model,
	'columns'=>array(
		'surat',
		'name',
		array(
			'header' => 'Tgl. Acara',
            'name' => 'schedule',
            'filter' => $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                'model'=>$model, 
                'attribute'=>'schedule', 
                'language' => 'id',
                'htmlOptions' => array(
                    'id' => 'datepicker_for_due_date',
                    'size' => '10',
                ),
                'defaultOptions' => array(  // (#3)
                    'showOn' => 'focus', 
                    'dateFormat' => 'yy/mm/dd',
                    'showOtherMonths' => true,
                    'selectOtherMonths' => true,
                    'changeMonth' => true,
                    'changeYear' => true,
                    'showButtonPanel' => true,
                )
            ), 
            true), 
            'value' => 'date("D / d M Y", strtotime($data->schedule))',
        ),
		array(
			'name'=> 'schedule',
			'header' => 'Waktu',
			'value' => 'date("H:i", strtotime($data->schedule))',
		),
		'place',
		'disposisi_nama',
		'disposisi_jabatan',
		array(
	        'name'=>'is_active',             
	        'value'=>'',
	        'type'=>'raw',
	        'htmlOptions'=>array('width'=>5),
	        'value'=>'sprintf(\'<input  onchange="toggleAktif(this.value);" type="checkbox" class="ace ace-switch ace-switch-5 toggle-status" %s  value="%s"  /><span class="lbl"></span>\', ($data->is_active == 1 ? \'checked="checked"\' : ""), $data->id)',
	        'filter' => array('1'=>'Ya','0'=>'Tidak'),
        ),
		array(
				'class'=>'CButtonColumn',
									'template'=>'{update} {delete}',
									'htmlOptions'=>array('class'=>'col-xs-2 col-sm-2 col-md-1'),
								    'buttons'=>array (
								        'update'=> array(
								            'label'=>'<i class="fa fa-pencil"></i>',
								            'imageUrl'=>false,
								            'options'=>array( 'title'=> 'Ubah', 'class'=>'btn btn-warning btn-xs' ),
								        ),								        
								        'delete'=>array(
								            'label'=>'<i class="fa fa-remove"></i>',
								            'imageUrl'=>false,
								            'options'=>array( 'title'=> 'Hapus', 'class'=>'btn btn-danger btn-xs' ),
								        ),
								    ),
			),
	),
)); ?>


<?php
$url = Yii::app()->createUrl('event/export');
$url_toggle = Yii::app()->createUrl('event/toggle');

$scripts=<<<EOL
var export_function = function(){
	var no_surat = 'surat=' + $( "input[name='Event[surat]']" ).val();
	var acara = 'name=' + $( "input[name='Event[name]']" ).val();
	var tgl_acara = 'schedule=' + $( "input[name='Event[schedule]']" ).val();
	var tempat = 'place=' + $( "input[name='Event[place]']" ).val();
	var disposisi_nama = 'disposisi_nama=' + $( "input[name='Event[disposisi_nama]']" ).val();
	var disposisi_jabatan = 'disposisi_jabatan=' + $( "input[name='Event[disposisi_jabatan]']" ).val();

	window.location='$url'+'&'+no_surat+'&'+acara+'&'+tgl_acara+'&'+tempat+'&'+disposisi_nama+'&'+disposisi_jabatan;
}

var toggleAktif = function(idnya){
	console.log('masuk');
	var url = '$url_toggle'+'&id='+idnya;
    window.location.assign(url);
}
EOL;

/*******
 * JavaScript
 *******/
Yii::app()->clientScript->registerScript('create-event', $scripts, CClientScript::POS_END);

protected/views/event/create.php
<?php
/* @var $this EventController */
/* @var $model Event */

$this->breadcrumbs=array(
	'Kegiatan'=>array('index'),
	'Tambah',
);

$this->menu=array(
	array('label'=>'List Event', 'url'=>array('index')),
);
$title = "Tambah Kegiatan";
?>

<h1><?php echo $title;?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>