protected/models/Info.php
<?php

/**
 * This is the model class for table "tbl_info".
 *
 * The followings are the available columns in table 'tbl_info':
 * @property integer $id
 * @property string $category
 * @property string $title
 * @property string $content
 * @property string $image_path
 * @property integer $is_active
 */
class Info extends CActiveRecord
{
	public $upload_dir = 'images/info/';
	public $image_file;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_info';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('category', 'length', 'max'=>100),
			array('title', 'length', 'max'=>150),
			array('image_path', 'length', 'max'=>250),
			array('content', 'safe'),
			array('upload_dir', 'directory_available'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, category, title, content, image_path, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function directory_available($attribute, $params)
	{
		$savePath = sprintf('%s..%s'
			, Yii::app()->getBasePath() . DIRECTORY_SEPARATOR
			, DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $this->upload_dir)
		);
		if (! file_exists($savePath)) {
			if (is_writable(dirname($savePath))) {
				if (! mkdir($savePath, 0777, true)) {
					$this->addError('image_file', 'Cannot create directory: '. $savePath);	
				}
			} else {
				$this->addError('image_file', 'Cannot create directory: '. dirname($savePath));
			}
		} elseif (! is_writable($savePath)) {
			$this->addError('image_file', 'Permission denied on: '. $savePath);
		}
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'category' => 'Kategori',
			'title' => 'Judul',
			'content' => 'Isi',
			'image_path' => 'Gambar',
			'is_active' => 'Aktif',
			'image_file' => 'Gambar',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('category',$this->category,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('is_active',$this->is_active,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Info the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	public function beforeSave()
	{
		$this->image_file = CUploadedFile::getInstance($this, 'image_file');
		if ($this->image_file != null) {
			$basedir = $this->upload_dir;
			$filename = sprintf('%s.%s'
				, sha1($this->image_file->getName() . time())
				, $this->image_file->getExtensionName()
			);
			$this->image_file->saveAs(Yii::app()->getBasePath() . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . $basedir . $filename);
			$this->image_path = $basedir . $filename;
		}
		return parent::beforeSave();
	}	
	public function scopes()
	{
		return array(
			'categoryList'=>array(
                'condition'=>'is_active = 1',
                'group'=>'category'
            ),
		);
	}

	public function randomize($category = null){
		$categories = CJSON::decode($category);
		
		$criteria = new CDbCriteria;
		$criteria->limit = 1;
		$criteria->addCondition('is_active = 1');
		$criteria->order = 'RAND()';

		if(count($categories) >= 1){
			$categories = CJSON::decode($category);
			$criteria->addInCondition('category', $categories);
		}

		return $this->find($criteria);
	}
}

protected/controllers/InfoController.php
<?php

class InfoController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request 
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  
				'actions'=>array('list'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update', 'index', 'view', 'delete', 'fetchCategory', 'fetchTitle','toggle'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Info;

		if(isset($_POST['Info']))
		{
			$model->attributes=$_POST['Info'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(isset($_POST['Info']))
		{
			$model->attributes=$_POST['Info'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Info('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Info']))
			$model->attributes=$_GET['Info'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Info the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Info::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Info $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='info-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionFetchCategory()
	{
		$criteria = new CDbCriteria();
		$criteria->select = 'DISTINCT category AS category';
		$criteria->compare('category', $_GET['term'], true);
		$list = Info::model()->findAll($criteria);
		$result = array();
		if (! empty($list)) {
			foreach ($list as $row) {
				array_push($result, $row->category);
			}
		}

		echo CJSON::encode($result);
	}
	public function actionFetchTitle()
	{
		$criteria = new CDbCriteria();
		$criteria->select = 'DISTINCT title AS title';
		$criteria->compare('title', $_GET['term'], true);
		$list = Info::model()->findAll($criteria);
		$result = array();
		if (! empty($list)) {
			foreach ($list as $row) {
				array_push($result, $row->title);
			}
		}

		echo CJSON::encode($result);
	}


	public function actionList(){
		$modelSetting = Setting::getDefault();
		$sidebar = $modelSetting->sidebar;

		$modelInfo = Info::model()->randomize($sidebar);
		$respone = array(
			'info' => array(
				'title'=>$modelInfo->title,
				'content'=>$modelInfo->content,
				'image_path'=>$modelInfo->image_path
			)
		);

		if(count($modelInfo) >= 1){
			header('Content-type: application/json');
			echo CJSON::encode($respone);
			Yii::app()->end();
		}else{
			throw new CHttpException("Data Kosong", 1);
		}
    }

	public function actionToggle($id)
	{  	
		$model = Info::model()->findByPk($id);
		$aktif = $model->is_active;

		if($aktif==1) {
			Info::model()->updateByPk($id, array('is_active' => 0 ));
		} else {
			Info::model()->updateByPk($id, array('is_active' => 1 ));
		}

		$this->redirect(array('index'));
	}
}

protected/views/info/_form.php
<?php
/* @var $this InfoController */
/* @var $model Info */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'info-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array(
		'enctype'=>'multipart/form-data',
		'class'=>"form-horizontal"
	),
)); ?>

	<p class="alert alert-block alert-success">Kolom dengan <span class="required">*</span> harus diisi</p>

	<?php $errornya= $form->errorSummary($model); 
	if (strlen($errornya)>1) { ?>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">
				<i class="ace-icon fa fa-times"></i>
			</button>
			<?php echo $form->errorSummary($model); ?>
			<br />
		</div>	
	<?php	} ?>
	
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="category"> <?php echo $form->labelEx($model,'category'); ?> </label>
		<div class="col-sm-9">
			<?php $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
			    'model'=>$model,
			    'attribute'=>'category',
			    'sourceUrl'=>Yii::app()->createUrl('info/fetchCategory'),
				    'options'=>array(
				        'minLength'=>'2',
				    ),
				    'htmlOptions'=>array('size'=>60,'maxlength'=>100, 'required'=>'required'),
			)); ?>
			<?php echo $form->error($model,'category'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="title"> <?php echo $form->labelEx($model,'title'); ?> </label>
		<div class="col-sm-9">
			<?php $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
			    'model'=>$model,
			    'attribute'=>'title',
			    'sourceUrl'=>Yii::app()->createUrl('info/fetchTitle'),
				    'options'=>array(
				        'minLength'=>'2',
				    ),
				    'htmlOptions'=>array('size'=>60,'maxlength'=>150, 'required'=>'required'),
			)); ?>
			<?php echo $form->error($model,'title'); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="content"> <?php echo $form->labelEx($model,'content'); ?> </label>
		<div class="col-sm-9">
			<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50, 'maxlength'=>'250','required'=>'required')); ?>
			<?php echo $form->error($model,'content'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="id-input-file-2"> <?php echo $form->labelEx($model,'image_file'); ?> </label>
		<div class="col-sm-9">
		    <?php echo $form->fileField($model,'image_file',array('id'=>'id-input-file-2')); ?>
			<?php echo $form->error($model,'image_file'); ?>
		</div>
	</div>

	<?php if (! empty($model->image_path)) : ?>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" for="image_path">  </label>
			<div class="col-sm-9">
				<?php 
					echo CHtml::image(
						Yii::app()->request->baseUrl.'/'.$model->image_path, 
						$model->title, 
						array(
							'width'=>'90%'
						)
					); 
				?>
			</div>
		</div>
	<?php endif; ?>

	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<?php echo CHtml::submitButton($model->isNewRecord ? ' Tambahkan' : '  Simpan', 
			array('class' => 'btn btn-primary', 'type' => 'submit')); ?>
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php

$scripts=<<<EOL
$('#id-input-file-2').ace_file_input({
	no_file:'No File ...',
	btn_choose:'Choose',
	btn_change:'Change',
	droppable:false,
	onchange:null,
	thumbnail:false, //| true | large
});
EOL;

Yii::app()->clientScript->registerScript('create-event', $scripts, CClientScript::POS_END);

protected/views/info/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'htmlOptions'=> ['class' => 'form-horizontal'],
	'method'=>'get', 
	)); ?>
	<div class="row">
		<?php echo $form->label($model,'category'); ?>
		<?php echo $form->textField($model,'category',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textField($model,'content',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>
</div>

protected/views/info/admin.php
<?php
/* @var $this InfoController */
/* @var $model Info */

$this->breadcrumbs=array(
	'Himbauan'=>array('index'),
	'Daftar',
);

$this->menu=array(
	array('label'=>'Create Info', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$('#info-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
$title = "Daftar Himbauan";
?>

<h1><?php echo $title; ?></h1>
<div class="table-responsive">
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'info-grid',
		'dataProvider'=>$model->search(),
		'itemsCssClass'=>'table table-striped table-bordered table-hover',
		'enableSorting'=>true,
		'filter'=>$model,
		'columns'=>array(
			'category',
			'title',
			'content',
			array(
				'type'=>'raw',
				'name'=>'is_active',
				'header' => 'Aktif',
				'value'=>'sprintf(\'<input onchange="toggleAktif(this.checked,this.value);" type="checkbox" class="ace ace-switch ace-switch-5 toggle-status" %s data-href="%s" value="%s"  /><span class="lbl"></span>\', ($data->is_active == 1 ? \'checked="checked"\' : ""), Yii::app()->createUrl("info/toggle", array("id"=>$data->id, "f"=>$data->is_active)), $data->id)',
				'filter'=>array('1'=>'Ya','0'=>'Tidak'),
			),
			array(
				'class'=>'CButtonColumn',
				'template'=>'{view}{update}{delete}',
				'htmlOptions'=>array('class'=>'col-xs-2 col-sm-2 col-md-2'),
			    'buttons'=>array (
			        'update'=> array(
			            'label'=>'<i class="fa fa-pencil"></i>',
			            'imageUrl'=>false,
			            'options'=>array( 'title'=> 'Ubah', 'class'=>'btn btn-warning btn-minier' ),
			        ),								        
			        'delete'=>array(
			            'label'=>'<i class="fa fa-remove"></i>',
			            'imageUrl'=>false,
			            'options'=>array( 'title'=> 'Hapus', 'class'=>'btn btn-danger btn-minier' ),
			        ),
			        'view'=>array(
			            'label'=>'<i class="fa fa-eye"></i>',
			            'imageUrl'=>false,
			            'options'=>array( 'title'=> 'View', 'class'=>'btn btn-info btn-minier' ),
			        ),
			    ),
			),
		),
	)); ?>
</div>

<script type="text/javascript">
function toggleAktif(cek,idnya){
	var url = "<?php echo Yii::app()->getBaseUrl(true); ?>/index.php?r=info/toggle&id="+idnya;
	//alert(url);
    window.location.assign(url);
}
</script>

protected/views/info/create.php
<?php
/* @var $this InfoController */
/* @var $model Info */

$this->breadcrumbs=array(
	'Himbauan'=>array('index'),
	'Tambah',
);

$this->menu=array(
	array('label'=>'List Info', 'url'=>array('index')),
);

$title = "Tambah Himbauan";
?>

<h1><?php echo $title;?></h1>
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/info/update.php
<?php
/* @var $this InfoController */
/* @var $model Info */

$this->breadcrumbs=array(
	'Himbauan'=>array('index'),
	'Rubah',
);

$this->menu=array(
	array('label'=>'List Info', 'url'=>array('index')),
	array('label'=>'Create Info', 'url'=>array('create')),
);
?>

<h1>Rubah Himbauan</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/info/view.php
<?php
/* @var $this InfoController */
/* @var $model Info */

$this->breadcrumbs=array(
	'Himbauan'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'List Info', 'url'=>array('index')),
	array('label'=>'Create Info', 'url'=>array('create')),
	array('label'=>'Update Info', 'url'=>array('update', 'id'=>$model->id)),
);
?>

<style type="text/css">
	.profile-picture img{
		width: 100%;
	}
</style>

<div class="tab-pane in active" id="home">
	<div class="row">
		<div class="col-xs-12 col-sm-3 center">
			<span class="profile-picture">
				<?php echo empty($model->image_path) ? 'Not set' : CHtml::image(Yii::app()->request->baseUrl.'/'.$model->image_path, $model->title);?>
			</span>
		</div><!-- /.col -->

		<div class="col-xs-12 col-sm-9">
			<h4 class="blue">
				<span class="middle"><?php echo $model->title;?></span>
				<?php 
					if($model->is_active == 1){ ?>
						<span class="label label-success arrowed">
							<i class="ace-icon glyphicon glyphicon-ok smaller-80 align-middle"></i>
							Aktif
						</span>
				<?php
					}else{ ?>
						<span class="label">
							<i class="ace-icon glyphicon glyphicon-remove  smaller-80 align-middle"></i>
							Tidak Aktif
						</span>
				<?php
					}
				?>
			</h4>

			<div class="profile-user-info">
				<div class="profile-info-row">
					<div class="profile-info-name"> Category </div>

					<div class="profile-info-value">
						<span><?php echo $model->category;?></span>
					</div>
				</div>

				<div class="profile-info-row">
					<div class="profile-info-name"> Isi Himbauan </div>

					<div class="profile-info-value">
						<span><?php echo $model->content;?></span>
					</div>
				</div>
			</div>
		</div><!-- /.col -->
	</div><!-- /.row -->
</div>