protected/models/User.php
<?php

/**
 * This is the model class for table "tbl_user".
 *
 * The followings are the available columns in table 'tbl_user':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $full_name
 * @property string $position
 * @property string $last_login
 */
class User extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('username, full_name', 'required'),
			array('password', 'required', 'on'=>'insert'),
			array('username, password, full_name', 'length', 'max'=>128),
			array('position', 'length', 'max'=>150),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, password, full_name, position, last_login, is_active', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'password' => 'Password',
			'full_name' => 'Nama Lengkap',
			'position' => 'Jabatan',
			'last_login' => 'Login Terakhir',
			'is_active' => 'Aktif'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('username',$this->username,true);
		$criteria->compare('full_name',$this->full_name,true);
		$criteria->compare('position',$this->position,true);
		$criteria->compare('last_login',$this->last_login,true);
		$criteria->compare('is_active',$this->is_active,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	public function beforeSave()
	{
		if (! empty($this->password)) 
			$this->password = sha1($this->password);		
		else 
			unset($this->password);
		// if($this->isNewRecord){
		// 	if (! empty($this->password)){
		// 		$this->password = sha1($this->password);
		// 	}else {
		// 		unset($this->password);
		// 	}
		// }else{
		// 	$modelOld = self::findByAttributes(array('id'=>$this->id));
		// 	if (! empty($this->password)){
		// 		if($this->password != $modelOld->password){
		// 			$this->password = sha1($this->password);
		// 		}
		// 	}else {
		// 		unset($this->password);
		// 	}
		// }

		return parent::beforeSave();
	}
	public static function markLogin($userID)
	{
		return User::model()->updateByPk($userID, array(
			'last_login'=>new CDbExpression('NOW()'),
		));
	}
	
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	// public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete','index','create','update', 'toggle'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		unset($model->password);
		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionToggle($id)
	{  	
		$model = User::model()->findByPk($id);
		$aktif = $model->is_active;
		
		if($aktif==1) {
			$model->is_active = 0;
			$model->save();
		} else {
			$model->is_active = 1;
			$model->save();
		}
		$this->redirect('index.php?r=user/index');
	}
}

protected/views/user/_form.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=> [
		'class' => 'form-horizontal'
	]
)); ?>

	<p class="alert alert-block alert-success">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php $errornya= $form->errorSummary($model); 
		if (strlen($errornya)>1) { ?>
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">
					<i class="ace-icon fa fa-times"></i>
				</button>
				<?php echo $form->errorSummary($model); ?>
				<br />
			</div>	
	<?php	} ?>
	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'username'); ?> </label>
		<div class="col-sm-9">
			<?php 
				echo $form->textField($model,'username',
					array(
						'id'=>"form-field-3", 
						'placeholder'=>"Username", 
						'class'=>"form-control", 
						'required'=>'required', 
						'size'=>60,
						'maxlength'=>128
					)
				); 
			?>
			<?php echo $form->error($model,'username'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'full_name'); ?> </label>
		<div class="col-sm-9">
			<?php echo $form->textField($model,'full_name',array( 'id'=>"form-field-4", 'placeholder'=>"Nama Lengkap", 'class'=>"form-control", 'required'=>'required' , 'size'=>60,'maxlength'=>128)); ?>
			<?php echo $form->error($model,'full_name'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'position'); ?> </label>
		<div class="col-xs-12 col-sm-9">						
			<?php 
				echo $form->dropDownList($model,'position', 
					array(
						'IT'=>'IT', 
						'Resepsionis'=>'Resepsionis', 
						'CS'=>'CS',
						'admin'=>'admin', 
					), 
					array(
						'class'=>"select2", 
						'required'=>'required'
					)
				); 
			?>
			<?php echo $form->error($model,'position'); ?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> <?php echo $form->labelEx($model,'password'); ?> </label>
			<div class="col-sm-9">
			<?php 
				echo $form->textField($model, 'password', 
					array( 
						'id'=>"form-field-1", 
						'placeholder'=>"Password", 
						'class'=>"form-control", 
						'size'=>50, 
						'maxlength'=>128, 
						// 'value'=>''
					)
				); 
			?>
			<?php echo $form->error($model,'password'); ?>
		</div>
	</div>

	<div class="clearfix form-actions">
					<div class="col-md-offset-3 col-md-9">
		<?php 
			echo CHtml::submitButton($model->isNewRecord ? ' Tambahkan' : '  Simpan', 
				array(
					'class' => 'btn btn-primary', 
					'type' => 'submit'
				)
			); 
		?>
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php

$scripts=<<<EOL
$('.select2').css('width','200px').addClass('tag-input-style').select2({
	allowClear:true
});
EOL;

/*******
 * JavaScript
 *******/
Yii::app()->clientScript->registerScript('create-event', $scripts, CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl ."/backend/js/select2.min.js", CClientScript::POS_END);

/*******
 * Css
 *******/
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl ."/backend/css/select2.min.css");

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'full_name'); ?>
		<?php echo $form->textField($model,'full_name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'position'); ?>
		<?php echo $form->textField($model,'position',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'last_login'); ?>
		<?php echo $form->textField($model,'last_login'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('full_name')); ?>:</b>
	<?php echo CHtml::encode($data->full_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('position')); ?>:</b>
	<?php echo CHtml::encode($data->position); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_login')); ?>:</b>
	<?php echo CHtml::encode($data->last_login); ?>
	<br />


</div>

protected/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'User'=>array('index'),
	'Daftar',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");

$title = "Daftar User";
?>

<h1><?php echo $title; ?></h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'itemsCssClass'=>'table table-striped table-bordered table-hover',
	'enableSorting'=>true,
	'filter'=>$model,
	'columns'=>array(
		'full_name',
		'username',
		'position',
		array('name'=> 'last_login',
			'header' => 'Login terakhir',
			'value' => 'date("d/m/Y H:i:s", strtotime($data->last_login))' 
		),
		array(
			'type'=>'raw',
			'name'=>'is_active',
			'header' => 'Aktif',
			'value'=>'sprintf(\'<input  onchange="toggleAktif(this.checked,this.value);" type="checkbox" class="ace ace-switch ace-switch-5 toggle-status" %s data-href="%s"  value="%s"  /><span class="lbl"></span>\', ($data->is_active == 1 ? \'checked="checked"\' : ""), Yii::app()->createUrl("user/toggle", array("id"=>$data->id, "f"=>$data->is_active)), $data->id)',
			'filter'=>array('1'=>'Ya','0'=>'Tidak'),
		),
		array(
				'class'=>'CButtonColumn',
									'template'=>'{update} {delete}',
									'htmlOptions'=>array('class'=>'col-xs-2 col-sm-2 col-md-1'),
								    'buttons'=>array (
								        'update'=> array(
								            'label'=>'<i class="fa fa-pencil"></i>',
								            'imageUrl'=>false,
								            'options'=>array( 'title'=> 'Ubah', 'class'=>'btn btn-warning btn-xs' ),
								        ),								        
								        'delete'=>array(
								            'label'=>'<i class="fa fa-remove"></i>',
								            'imageUrl'=>false,
								            'options'=>array( 'title'=> 'Hapus', 'class'=>'btn btn-danger btn-xs' ),
								        ),
								    ),
			),
	),
)); ?>

<script type="text/javascript">
function toggleAktif(cek,idnya){
	var url = "<?php echo Yii::app()->getBaseUrl(true); ?>/index.php?r=user/toggle&id="+idnya;
	//alert(url);
    window.location.assign(url);
}
</script>

protected/views/user/create.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'User'=>array('index'),
	'Tambah',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
);
?>

<h1>Tambah User</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Users',
);

$this->menu=array(
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Users</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/user/update.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Rubah',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);
?>

<h1>Rubah User <?php echo $model->username; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/view.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>View User #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',
		'password',
		'full_name',
		'position',
		'last_login',
	),
)); ?>